name: "performance testing"

on: 
    push: 
        branches: 
            main


jobs:
    on-push:
        if: github.event_name == 'push'
        runs-on: ubuntu-latest
        steps:
            - name: "checkout code"
              uses: actions/checkout@v3
            - name: "setup python"
              uses: actions/setup-python@v4
              with:
                python-version: "3.9"
            - name: "start flask app"
              run: |
                nohup python app.py &
                sleep 15
            - name: "install k6"
              run: |
                curl -fsSL https://dl.k6.io/key.gpg | sudo gpg --dearmor -o /etc/apt/trusted.gpg.d/k6.gpg
                echo "deb [signed-by=/etc/apt/trusted.gpg.d/k6.gpg] https://dl.k6.io/deb stable main" | sudo tee /etc/apt/sources.list.d/k6.list
            
                sudo apt update
                sudo apt install -y k6

            - name: "run test on k6"
              run: k6 run test.js